### ISSUE TITLE
Suggestion: Large Heat Exchange support? 

### ISSUE THREAD

**Issue by Muramasa-** [GTNewHorizons/Minetweaker-Gregtech-5-Addon#8]
Is it possible to support the Large Heat Exchange in GT5E ?

I have dived into the GT code myself and there doesn't seem to be a method for it with the Recipe Adder. Does this mean it can't be supported?

Thanks, and sorry if this is already well known.

**Comment by Dream-Master** [comment]
I think i can do here much. Maybe fork gt code and change what you want to change.

**Comment by Dream-Master** [comment]
Will look into this again and check the code later.

**Comment by Techlone** [comment]
Not possible because it's [hardcoded](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_HeatExchanger.java#L107-L116).
LHE don't use a recipe list so maybe @Blood-Asp will decide to change it someday :)
@Muramasa- do you want to add a recipe? What kind?

**Comment by Muramasa-** [comment]
My use was the ability to heat steam with plasmas, but since this issue was posted I realized that it would have to create a crazy amount of steam and isn't really sensible.

You're welcome to close this since it's hardcoded and my use has turned to not make much sense :)
